name: My Jekyll Website
collections_dir: my_collections
collections:
  baked-goods:
    output: true
    name: baked-goods
    collection_type: recipe-category
    permalink: /baked-goods/:name
  beverages:
    output: true
    name: beverages
    collection_type: recipe-category
    permalink: /beverages/:name
  breakfast:
    output: true
    name: breakfast
    collection_type: recipe-category
    permalink: /breakfast/:name
  components:
    output: true
    name: components
    collection_type: recipe-category
    permalink: /components/:name
  desserts:
    output: true
    name: desserts
    collection_type: recipe-category
    permalink: /desserts/:name
  fish:
    output: true
    name: fish
    collection_type: recipe-category
    permalink: /fish/:name

